data:
  path: C:/Aravind's File/Projects/Sales-Prediction/data/
  sales_data: Walmart.csv
  preprocessed_data: preprocessed_data.parquet
  feature_engineered_data: feature_engineered_data.parquet
  model_input_data: model_input_data.parquet

# preprocessing:
#   missing_values:
#     Saving accounts: 'Unknown'
#     Checking account: 'Unknown'
#   scaling:
#     - Age
#     - Credit amount
#     - Duration

# feature_engineering:
#   one_hot_encoding:
#     - Job
#     - Housing
#     - Saving accounts
#     - Checking account
#     - Purpose
#     - Sex